apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-system-02-testapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/backstage-test-1/test-system-02-testapi
    targetRevision: main
    path: k8s
    directory:
      exclude: 'argocd-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: test-system-02
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
